name: medigo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # Icon cho iOS
  cupertino_icons: ^1.0.8
  
  # Gọi API (Kết nối Server)
  http: ^1.2.0
  
  # Định dạng tiền tệ (VND)
  intl: ^0.19.0
  
  # Lưu thông tin đăng nhập vào bộ nhớ máy (QUAN TRỌNG)
  shared_preferences: ^2.2.2

  # Mở link trong trình duyệt (trang Quản trị)
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "../assets/c__Users_ADMIN_AppData_Roaming_Cursor_User_workspaceStorage_b51fa1abeb94bd4412da6f8333395a18_images_app_tr_m_thu_c-a364d170-02b1-4afd-9ffe-3d2a7b0e050d.png"