"""init

Revision ID: a81d1c0d5f4d
Revises: 
Create Date: 2026-02-14 17:35:47.758703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a81d1c0d5f4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_constraint(batch_op.f('order_details_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('order_details_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('orders_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_products_categories'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_products_categories'), 'categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_details_ibfk_1'), 'orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('order_details_ibfk_2'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
